import json
from datetime import datetime

def seed_checklists():
    master_path = 'public/data/geotech_master.json'
    with open(master_path, 'r', encoding='utf-8') as f:
        master = json.load(f)

    # Inspeções de exemplo no padrão exato do Survey123 - Formulário de Inspeção Regular - FIR - R0
    initial_checklists = [
        {
            "id": "FIR-202609-001",
            "surveyId": "8f6f56e94ec142af90e2ac9084ce716c",
            "titulo": "Formulário de Inspeção Regular - FIR - R0",
            "data": "2026-09-15",
            "hora": "09:30",
            "estrutura": "Barragem B1",
            "estruturaId": "BARRAGEM_B1",
            "profissional": "Eng. Marcelo N. Siqueira (CREA 85.120/D-MG)",
            "condicoesClimaticas": "Ensolarado",
            "volumeAcumulado": 14.8,
            "vazaoHm": 2.15,
            "lat": -20.063818,
            "lon": -44.114360,
            "acessos": "Bom",
            "acessosObs": "Pistas de acesso limpas, sem atolamentos e com canaletas laterais operacionais.",
            "macicoCondicoesEstruturais": "Não detectado",
            "macicoCondicoesVisuais": "Não detectado",
            "macicoCondicoesSuperficiais": "Não detectado",
            "macicoObs": "Taludes de montante e jusante estáveis. Ausência de trincas, trincamento em crista ou escorregamentos.",
            "drenagemSuperficial": "Não",
            "tipoObstrucao": "Nenhum",
            "estadoConservacaoDrenagem": "Bom",
            "drenagemObs": "Canaletas de berma desobstruídas e descidas d'água em bom estado de conservação.",
            "reservatorioQualidadeAgua": "Límpida",
            "nivelAssoreamento": "Baixo",
            "taludeMontante": "Estável",
            "reservatorioObs": "Borda livre de 3.85 m mantida. Sem presença de troncos ou corpos flutuantes junto à crista.",
            "drenagemInterna": "Operando Normal",
            "qualidadeAguaDrenagem": "Límpida",
            "estadoGeralDrenagemInterna": "Bom",
            "drenagemInternaObs": "Vazão do dreno de pé límpida com 2.15 L/s, sem carreamento de sedimentos.",
            "instrumentacao": "Operando Normalmente",
            "condicoesGeraisInstrumentacao": "Bom",
            "tipoInstrumento": ["Piezômetros (INA/PZ)", "Marcos Superficiais", "Vertedouros (VT)"],
            "tampasProtecao": "Íntegras",
            "instrumentacaoObs": "Todos os piezômetros com tampas trancadas e identificação legível.",
            "sistemaExtravasor": "Não",
            "tipoObstrucaoExtravasor": "Nenhum",
            "condicoesFluxo": "Livre",
            "estadoConservacaoExtravasor": "Bom",
            "extravasorObs": "Calha do vertedouro de concreto íntegra, sem fissuras ou desagregações.",
            "matrizANM": {
                "confiabilidadeExtravasor": "Excelente",
                "percolacao": "Normal / Controlada",
                "deformacaoRecalques": "Imperceptível",
                "deterioracaoTaludes": "Nenhuma",
                "drenagemSuperficial": "Totalmente Operacional"
            },
            "classificacaoGeral": "Conforme / Nível Normal",
            "status": "CONFORME",
            "badgeClass": "badge-normal",
            "observacoesFinais": "Estrutura apresenta condições de estabilidade satisfatórias, em plena conformidade com a Resolução ANM nº 95/2022.",
            "acoesRecomendadas": "Manter cronograma de inspeções ordinárias quinzenais e monitoramento contínuo dos piezômetros.",
            "fotoUrl": "/assets/fir_inspecao_b1.jpg",
            "linkSurvey": "https://arcg.is/0yOmKX0"
        },
        {
            "id": "FIR-202609-002",
            "surveyId": "8f6f56e94ec142af90e2ac9084ce716c",
            "titulo": "Formulário de Inspeção Regular - FIR - R0",
            "data": "2026-09-14",
            "hora": "14:15",
            "estrutura": "Cava Jangada",
            "estruturaId": "JANGADA",
            "profissional": "Geol. Carlos Eduardo M. (CREA 42.980/D-MG)",
            "condicoesClimaticas": "Nublado",
            "volumeAcumulado": 18.2,
            "vazaoHm": 4.80,
            "lat": -20.096200,
            "lon": -44.088500,
            "acessos": "Regular",
            "acessosObs": "Trecho da rampa de acesso sul com acúmulo pontual de brita, necessitando patrolamento leve.",
            "macicoCondicoesEstruturais": "Não detectado",
            "macicoCondicoesVisuais": "Atenção",
            "macicoCondicoesSuperficiais": "Não detectado",
            "macicoObs": "Presença de surgência natural mapeada na bancada intermediária (Cota 1020m). Vazão estável e monitorada.",
            "drenagemSuperficial": "Sim",
            "tipoObstrucao": "Sedimentos",
            "estadoConservacaoDrenagem": "Regular",
            "drenagemObs": "Canaleta da berma 03 com leve assoreamento após chuvas de agosto.",
            "reservatorioQualidadeAgua": "Límpida",
            "nivelAssoreamento": "Médio",
            "taludeMontante": "Estável",
            "reservatorioObs": "Sump de fundo de cava operando com bombeamento regular.",
            "drenagemInterna": "Operando Normal",
            "qualidadeAguaDrenagem": "Límpida",
            "estadoGeralDrenagemInterna": "Regular",
            "drenagemInternaObs": "Vertedouros trapezoidais da bacia Jangada/Engenho Seco com leitura aferida (4.80 L/s).",
            "instrumentacao": "Operando Normalmente",
            "condicoesGeraisInstrumentacao": "Bom",
            "tipoInstrumento": ["Piezômetros (INA)", "Vertedouros (VT)"],
            "tampasProtecao": "Íntegras",
            "instrumentacaoObs": "26 INAs e 21 vertedouros inspecionados. Leituras em dia.",
            "sistemaExtravasor": "Não",
            "tipoObstrucaoExtravasor": "Nenhum",
            "condicoesFluxo": "Livre",
            "estadoConservacaoExtravasor": "Bom",
            "extravasorObs": "Drenagem da cava direcionada ao desvio de águas pluviais.",
            "matrizANM": {
                "confiabilidadeExtravasor": "Satisfatória",
                "percolacao": "Surgência Monitorada",
                "deformacaoRecalques": "Imperceptível",
                "deterioracaoTaludes": "Estável",
                "drenagemSuperficial": "Parcialmente Obstruída"
            },
            "classificacaoGeral": "Atenção Operacional",
            "status": "ATENÇÃO",
            "badgeClass": "badge-atencao",
            "observacoesFinais": "Estrutura estável. Recomendada limpeza imediata da canaleta da berma 03 para evitar acúmulo de águas pluviais.",
            "acoesRecomendadas": "Realizar desassoreamento da canaleta da berma 03 e acompanhar surgência na cota 1020m.",
            "fotoUrl": "/assets/fir_inspecao_jgd.jpg",
            "linkSurvey": "https://arcg.is/0yOmKX0"
        },
        {
            "id": "FIR-202609-003",
            "surveyId": "8f6f56e94ec142af90e2ac9084ce716c",
            "titulo": "Formulário de Inspeção Regular - FIR - R0",
            "data": "2026-09-12",
            "hora": "10:00",
            "estrutura": "Barragem B4",
            "estruturaId": "BARRAGEM_B4",
            "profissional": "Eng. Marcelo N. Siqueira (CREA 85.120/D-MG)",
            "condicoesClimaticas": "Ensolarado",
            "volumeAcumulado": 12.0,
            "vazaoHm": 1.10,
            "lat": -20.061200,
            "lon": -44.112800,
            "acessos": "Bom",
            "acessosObs": "Acessos à crista e bermas em perfeitas condições de tráfego.",
            "macicoCondicoesEstruturais": "Não detectado",
            "macicoCondicoesVisuais": "Não detectado",
            "macicoCondicoesSuperficiais": "Não detectado",
            "macicoObs": "Sem indícios de recalques ou movimentações de massa. Cobertura vegetal homogênea.",
            "drenagemSuperficial": "Não",
            "tipoObstrucao": "Nenhum",
            "estadoConservacaoDrenagem": "Bom",
            "drenagemObs": "Drenos e canaletas limpos e sem trincas.",
            "reservatorioQualidadeAgua": "Límpida",
            "nivelAssoreamento": "Baixo",
            "taludeMontante": "Estável",
            "reservatorioObs": "Nível de água respeitando a cota máxima de operação.",
            "drenagemInterna": "Operando Normal",
            "qualidadeAguaDrenagem": "Límpida",
            "estadoGeralDrenagemInterna": "Bom",
            "drenagemInternaObs": "Drenos sub-horizontais e dreno de pé com vazão contínua e límpida.",
            "instrumentacao": "Operando Normalmente",
            "condicoesGeraisInstrumentacao": "Bom",
            "tipoInstrumento": ["Piezômetros de Corda Vibrante", "Marcos Superficiais", "Medidores de Nível"],
            "tampasProtecao": "Íntegras",
            "instrumentacaoObs": "116 instrumentos ativos. Telemetria automática operando sem interrupções.",
            "sistemaExtravasor": "Não",
            "tipoObstrucaoExtravasor": "Nenhum",
            "condicoesFluxo": "Livre",
            "estadoConservacaoExtravasor": "Bom",
            "extravasorObs": "Tulipa e galeria extravasora em perfeito estado de operação.",
            "matrizANM": {
                "confiabilidadeExtravasor": "Excelente",
                "percolacao": "Totalmente Controlada",
                "deformacaoRecalques": "Nenhum",
                "deterioracaoTaludes": "Nenhuma",
                "drenagemSuperficial": "Excelente"
            },
            "classificacaoGeral": "Conforme / Nível Normal",
            "status": "CONFORME",
            "badgeClass": "badge-normal",
            "observacoesFinais": "Estrutura com índice de segurança plenamente satisfatório.",
            "acoesRecomendadas": "Manter acompanhamento sistemático conforme PAEBM.",
            "fotoUrl": "/assets/fir_inspecao_b4.jpg",
            "linkSurvey": "https://arcg.is/0yOmKX0"
        },
        {
            "id": "FIR-202609-004",
            "surveyId": "8f6f56e94ec142af90e2ac9084ce716c",
            "titulo": "Formulário de Inspeção Regular - FIR - R0",
            "data": "2026-09-10",
            "hora": "15:45",
            "estrutura": "PDE Mangaba",
            "estruturaId": "PDE_MANGABA",
            "profissional": "Téc. Roberto Alves (CFT 12.340-MG)",
            "condicoesClimaticas": "Ensolarado",
            "volumeAcumulado": 10.5,
            "vazaoHm": 0.45,
            "lat": -20.065500,
            "lon": -44.116200,
            "acessos": "Bom",
            "acessosObs": "Acesso desobstruído.",
            "macicoCondicoesEstruturais": "Não detectado",
            "macicoCondicoesVisuais": "Não detectado",
            "macicoCondicoesSuperficiais": "Não detectado",
            "macicoObs": "Pilha de estéril compactada conforme projeto executivo.",
            "drenagemSuperficial": "Não",
            "tipoObstrucao": "Nenhum",
            "estadoConservacaoDrenagem": "Bom",
            "drenagemObs": "Canaletas em escada operando normalmente.",
            "reservatorioQualidadeAgua": "Límpida",
            "nivelAssoreamento": "Baixo",
            "taludeMontante": "Estável",
            "reservatorioObs": "Bacia de sedimentação de jusante com capacidade livre.",
            "drenagemInterna": "Operando Normal",
            "qualidadeAguaDrenagem": "Límpida",
            "estadoGeralDrenagemInterna": "Bom",
            "drenagemInternaObs": "Dreno de pé sem acúmulo de partículas sólidas.",
            "instrumentacao": "Operando Normalmente",
            "condicoesGeraisInstrumentacao": "Bom",
            "tipoInstrumento": ["Marcos Topográficos"],
            "tampasProtecao": "Íntegras",
            "instrumentacaoObs": "7 marcos topográficos sem deslocamento significativo.",
            "sistemaExtravasor": "Não",
            "tipoObstrucaoExtravasor": "Nenhum",
            "condicoesFluxo": "Livre",
            "estadoConservacaoExtravasor": "Bom",
            "extravasorObs": "Vertedouro de bacia com passagem livre.",
            "matrizANM": {
                "confiabilidadeExtravasor": "Boa",
                "percolacao": "Seco",
                "deformacaoRecalques": "Nenhum",
                "deterioracaoTaludes": "Estável",
                "drenagemSuperficial": "Boa"
            },
            "classificacaoGeral": "Conforme / Nível Normal",
            "status": "CONFORME",
            "badgeClass": "badge-normal",
            "observacoesFinais": "Pilha e bacias de amortecimento em conformidade com as diretrizes geotécnicas.",
            "acoesRecomendadas": "Manter rotina mensal de vistorias visuais e marcos.",
            "fotoUrl": "/assets/fir_inspecao_mangaba.jpg",
            "linkSurvey": "https://arcg.is/0yOmKX0"
        }
    ]

    master['checklists'] = initial_checklists

    with open(master_path, 'w', encoding='utf-8') as f:
        json.dump(master, f, indent=2, ensure_ascii=False)

    print("Checklists do Survey123 adicionados com sucesso ao master json!")

    scratch_master = r'C:\Users\maycon.nascimento\.gemini\antigravity-ide\scratch\mdsync-geotecnia\public\data\geotech_master.json'
    try:
        with open(scratch_master, 'w', encoding='utf-8') as f:
            json.dump(master, f, indent=2, ensure_ascii=False)
        print("Salvo também em scratch!")
    except Exception as e:
        print("Aviso scratch:", e)

if __name__ == '__main__':
    seed_checklists()
